service: task-management

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    AWS_REGION: us-east-1
    DB_HOST: ${env.DB_HOST}
    PORT: ${env.PORT}
    DB_USER: ${env.DB_USER}
    DB_PASSWORD: ${env.DB_PASSWORD}
    DB_NAME: ${env.DB_NAME}
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  app:
    handler: handler.main  # Debe coincidir con la exportación en handler.js
    events:
      - httpApi:
          path: /tasks/admin
          method: GET
      - httpApi:
          path: /tasks/admin
          method: POST
      - httpApi:
          path: /tasks/admin/{id}
          method: GET
      - httpApi:
          path: /tasks/admin/{id}
          method: DELETE
      - httpApi:
          path: /tasks/admin/{id}
          method: PUT
      - httpApi:
          path: /tasks
          method: GET
      - httpApi:
          path: /tasks/{id}
          method: GET
      - httpApi:
          path: /tasks
          method: POST
      - httpApi:
          path: /users/register
          method: POST
      - httpApi:
          path: /users/login
          method: POST
      - httpApi:
          path: /users
          method: GET
      - httpApi:
          path: /users/role/{role}
          method: GET
      - httpApi:
          path: /users/{id}
          method: PUT
      - httpApi:
          path: /users/admin/{id}
          method: PUT
      - httpApi:
          path: /users/{id}
          method: DELETE
plugins:
  - serverless-dotenv-plugin
  - serverless-offline

